# App
app:
  name: YOUR_APP_NAME_HERE
  secret-code: YOUR_APP_SECRET_CODE_HERE

# Spring DataSource
spring.datasource:
  url: jdbc:mysql://localhost:3306/YOUR_DATABASE_NAME_HERE?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password: boris1997

  # If the connection is too long in idle state
  dbcp.test-while-idle: true
  dbcp.validation-query: SELECT 1
  initialization-mode: always

# JPA-Hibernate
spring.jpa:
  show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: create-drop
    naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
